task :default => 'morning:turn_off_alarm'

namespace :morning do
 task :groom_myself do
  puts "Brushed teeth"
  puts "Showered"
 end
end

namespace :morning do
 task :turn_off_alarm do
  puts "Turn off alarm. get up"
 end
end 

